#define EQUAL                           1
#define ADDEQ                           2
#define SUBEQ                           3
#define ANDEQ                           4
#define OREQ                            5
#define DIVEQ                           6
#define MULEQ                           7
#define MODEQ                           8
#define LSHEQ                           9
#define RSHEQ                          10
#define XOREQ                          11
#define QUESTION                       12
#define COLON                          13
#define OROR                           14
#define ANDAND                         15
#define VBAR                           16
#define CARET                          17
#define AMPERSAND                      18
#define EQ                             19
#define NE                             20
#define GT                             21
#define GE                             22
#define LE                             23
#define LT                             24
#define LSHIFT                         25
#define RSHIFT                         26
#define ADD                            27
#define SUB                            28
#define ASTERISK                       29
#define SLASH                          30
#define MOD                            31
#define NOT                            32
#define INCR                           33
#define DECR                           34
#define PRE                            35
#define LBRACKET                       36
#define RBRACKET                       37
#define POINTER                        38
#define PERIOD                         39
#define POST                           40
#define PROGRAM                        41
#define NAME                           42
#define LPAREN                         43
#define RPAREN                         44
#define SEMICOLON                      45
#define LBRACE                         46
#define RBRACE                         47
#define ASSIGN                         48
#define CONNECT                        49
#define TO                             50
#define COMMA                          51
#define MONITOR                        52
#define SYNC                           53
#define SYNCQ                          54
#define INTCON                         55
#define CHAR                           56
#define SHORT                          57
#define INT                            58
#define LONG                           59
#define UNSIGNED                       60
#define INT8T                          61
#define UINT8T                         62
#define INT16T                         63
#define UINT16T                        64
#define INT32T                         65
#define UINT32T                        66
#define FLOAT                          67
#define DOUBLE                         68
#define STRING                         69
#define EVFLAG                         70
#define FOREIGN                        71
#define OPTION                         72
#define SS                             73
#define STATE                          74
#define ENTRY                          75
#define EXIT                           76
#define WHEN                           77
#define BREAK                          78
#define CONTINUE                       79
#define IF                             80
#define ELSE                           81
#define WHILE                          82
#define FOR                            83
#define FPCON                          84
#define TILDE                          85
#define STRCON                         86
#define CCODE                          87
